const GH = "https://raw.githubusercontent.com/olha-droid748/icons/main/";
const ic = (n) => `${GH}${encodeURIComponent(n)}.png`;

export const APPS = [
  // ── REQUIRED TOP 5 ────────────────────────────────────────────────────────
  {
    name: "CleanMyMac",
    url: "https://setapp.com/apps/cleanmymac",
    reason: "Your Mac's been working hard — and it shows. CleanMyMac clears out the junk, kills hidden malware, and makes everything feel snappy again.",
    tags: ["productivity","performance","cleanup","speed","system","maintenance","clutter","messy","overwhelm","memory","storage","files","optimization","efficiency","tech","security","malware","protection"],
    logo: ic("CleanMyMac"),
    required: true,
  },
  {
    name: "Bartender",
    url: "https://setapp.com/apps/bartender",
    reason: "Too many icons fighting for attention up top? Bartender quietly tucks away the clutter so your menu bar only shows what actually matters.",
    tags: ["productivity","organization","workflow","efficiency","shortcuts","optimization","context-switching","apps","navigation","focus","attention","clarity","cleanup","clutter","overwhelm"],
    logo: ic("Bartender"),
    required: true,
  },
  {
    name: "iStat Menus",
    url: "https://setapp.com/apps/istat-menus",
    reason: "Something's slowing your Mac down but you don't know what. iStat Menus shows you exactly — CPU, memory, network — right from the menu bar.",
    tags: ["tech","productivity","analysis","data","systems","efficiency","optimization","tracking","performance","cleanup","speed","system","maintenance","clutter","overwhelm","memory","monitoring","hardware"],
    logo: ic("iStat Menus"),
    required: true,
  },
  {
    name: "CleanShot X",
    url: "https://setapp.com/apps/cleanshot",
    reason: "Take a screenshot, annotate it, blur the sensitive bits, and share a link — all before you'd even find the screenshot in Finder.",
    tags: ["productivity","creative","design","video","content","visual","communication","workflow","remote","capture","screenshots","files","efficiency","shortcuts","optimization","clarity","output","documentation","ocr","screen recording"],
    logo: ic("CleanShot"),
    required: true,
  },
  {
    name: "Paste",
    url: "https://setapp.com/apps/paste",
    reason: "Never lose something you copied ever again. Paste keeps your whole clipboard history searchable and synced across every device.",
    tags: ["productivity","organization","business","admin","workflow","efficiency","shortcuts","optimization","search","structure","retrieval","context-switching","time-loss","mental-load","clarity","performance","capture","text","code","information","systems","repetitive"],
    logo: ic("Paste"),
    required: true,
  },
  {
    name: "Downie",
    url: "https://setapp.com/apps/downie",
    reason: "Save videos from YouTube, Vimeo, and hundreds of other sites in one click — no browser extensions, no fuss.",
    tags: ["creative","video","content","media","research","entertainment","download","files","productivity","efficiency","study","learning","capture","output","visual","remote"],
    logo: ic("Downie"),
    required: true,
  },

  // ── EXTENDED POOL ──────────────────────────────────────────────────────────
  {
    name: "Craft",
    url: "https://setapp.com/apps/craft",
    reason: "Write, plan, and think — all in one place. Craft makes your notes feel like real documents, not a pile of text dumps.",
    tags: ["productivity","creative","writing","communication","documents","text","study","research","learning","notes","information","organization","business","management","workflow","remote","documentation","pdf","storage","efficiency","optimization","structure","retrieval","clarity","output"],
    logo: ic("Craft"),
  },
  {
    name: "NotePlan",
    url: "https://setapp.com/apps/noteplan",
    reason: "Your calendar, tasks, and notes finally live in the same place. Plan your day once and actually stick to it.",
    tags: ["productivity","organization","writing","text","notes","information","research","tasks","todo","planning","tracking","time-management","mental-load","clarity","efficiency","optimization","documentation","capture","automation","shortcuts","business","admin","workflow","pkm","calendar","reminders","management","study","learning","focus","deep-work","structure","retrieval","memory","overwhelm","output"],
    logo: ic("NotePlan"),
  },
  {
    name: "Spark Mail",
    url: "https://setapp.com/apps/spark-mail",
    reason: "Stop drowning in email. Spark surfaces what matters, hides what doesn't, and helps you write replies in half the time.",
    tags: ["productivity","communication","writing","information","organization","business","admin","operations","management","workflow","remote","efficiency","optimization","search","structure","retrieval","context-switching","tasks","planning","tracking","time-management","mental-load","clarity","overwhelm","reminders","email","output"],
    logo: ic("Spark Mail"),
  },
  {
    name: "Canary Mail",
    url: "https://setapp.com/apps/canary-mail",
    reason: "Your inbox writes back. Canary drafts replies before you even open the thread — just review, tweak, and send.",
    tags: ["communication","email","productivity","writing","ai","organization","business","workflow","efficiency","automation","management","privacy","security","information","capture","summarization","analysis","tasks","planning","time-management","mental-load","clarity","reminders","overwhelm","output"],
    logo: ic("Canary Mail"),
  },
  {
    name: "Session",
    url: "https://setapp.com/apps/session",
    reason: "Block the sites, set the timer, do the work. Session makes deep focus feel less like willpower and more like a system.",
    tags: ["productivity","focus","workflow","time-management","tasks","tracking","distraction","deep-work","attention","mental-load","clarity","performance","efficiency","optimization","organization","business","management","remote","freelance"],
    logo: ic("Session"),
  },
  {
    name: "Focused Work",
    url: "https://setapp.com/apps/focused-work-mac",
    reason: "Build a focus habit that actually sticks. Customisable sessions, distraction blocking, and a scratch pad for thoughts that pop up mid-flow.",
    tags: ["productivity","focus","organization","management","workflow","efficiency","optimization","planning","tracking","distraction","deep-work","attention","time-management","mental-load","clarity","reminders","overwhelm","output","pomodoro"],
    logo: ic("Focus 2"),
  },
  {
    name: "HazeOver",
    url: "https://setapp.com/apps/hazeover",
    reason: "Everything except your active window fades into the background. Surprisingly effective at keeping you in the zone.",
    tags: ["productivity","focus","deep-work","attention","distraction","workflow","context-switching","efficiency","optimization","clarity","mental-load","performance"],
    logo: ic("HazeOver"),
  },
  {
    name: "Mosaic",
    url: "https://setapp.com/apps/mosaic",
    reason: "Stop wrestling your windows into place. Mosaic snaps them into layouts you actually want, across however many screens you've got.",
    tags: ["productivity","organization","workflow","systems","apps","efficiency","optimization","context-switching","navigation","time-loss","mental-load","clarity","cleanup","clutter","overwhelm","window-management","multi-screen"],
    logo: ic("Mosaic"),
  },
  {
    name: "Workspaces",
    url: "https://setapp.com/apps/workspaces",
    reason: "Switch projects without the chaos. Open your whole context — apps, files, URLs — with one click.",
    tags: ["productivity","organization","workflow","efficiency","optimization","context-switching","apps","navigation","time-loss","tasks","planning","tracking","focus","deep-work","attention","time-management","mental-load","clarity","business","admin","remote","freelance","management","information","files","email","browsing","automation","systems"],
    logo: ic("Workspaces"),
  },
  {
    name: "Timing",
    url: "https://setapp.com/apps/timing",
    reason: "Track every hour you work without touching a timer. Timing builds your day's timeline automatically — you just review it.",
    tags: ["productivity","organization","business","admin","management","workflow","freelance","remote","clients","finance","consulting","analysis","data","reports","accuracy","systems","meetings","efficiency","optimization","tracking","tasks","planning","deep-work","time-management","mental-load","clarity","performance","overwhelm","output"],
    logo: ic("Timing"),
  },
  {
    name: "Taskheat",
    url: "https://setapp.com/apps/taskheat",
    reason: "See all your tasks as a flowchart, not a list. Finally understand what actually needs to happen first.",
    tags: ["productivity","organization","business","management","workflow","efficiency","optimization","tasks","todo","planning","tracking","time-management","mental-load","clarity","overwhelm","reminders"],
    logo: ic("Taskheat"),
  },
  {
    name: "GoodTask",
    url: "https://setapp.com/apps/goodtask",
    reason: "Power-user task management built right on top of Apple Reminders. Your existing tasks get a serious upgrade.",
    tags: ["productivity","organization","management","workflow","tasks","todo","planning","tracking","time-management","mental-load","clarity","reminders","overwhelm","efficiency","optimization","business","admin","operations","documents"],
    logo: ic("GoodTask"),
  },
  {
    name: "Godspeed",
    url: "https://setapp.com/apps/godspeed",
    reason: "Capture tasks as fast as you think them. Type naturally, hit enter, and Godspeed figures out the rest.",
    tags: ["productivity","organization","business","management","workflow","efficiency","shortcuts","optimization","tasks","todo","planning","tracking","time-management","mental-load","clarity","reminders","overwhelm","output","collaboration","communication","email","notes"],
    logo: ic("IMt"),
  },
  {
    name: "Unclutter",
    url: "https://setapp.com/apps/unclutter",
    reason: "A hidden panel that's always one scroll away. Notes, clipboard history, and temporary files — without cluttering your desktop.",
    tags: ["productivity","organization","notes","information","capture","files","storage","efficiency","shortcuts","optimization","search","retrieval","context-switching","apps","navigation","time-loss","mental-load","clarity","cleanup","system","maintenance","clutter","messy","overwhelm","reminders","output"],
    logo: ic("Unclutter"),
  },
  {
    name: "Yoink",
    url: "https://setapp.com/apps/yoink",
    reason: "Pick up a file, do something else, then drop it exactly where you need it. Yoink is the shelf your Mac never had.",
    tags: ["productivity","organization","workflow","efficiency","shortcuts","optimization","context-switching","apps","navigation","capture","files","storage","system","clutter","information","text","mental-load","clipboard","clarity","memory","retrieval","performance","tasks"],
    logo: ic("Yoink"),
  },
  {
    name: "Archiver",
    url: "https://setapp.com/apps/archiver",
    reason: "Zip, unzip, preview, and password-protect archives — without ever opening Terminal.",
    tags: ["productivity","files","storage","efficiency","organization","automation","shortcuts","optimization","system","maintenance","cleanup","security","data","business","admin","operations","workflow","management","encryption"],
    logo: ic("Archiver"),
  },
  {
    name: "Spotless",
    url: "https://setapp.com/apps/spotless",
    reason: "Set rules for where files should go and Spotless handles the rest. A tidy desktop on autopilot.",
    tags: ["productivity","organization","workflow","automation","systems","files","storage","efficiency","repetitive","optimization","structure","retrieval","cleanup","system","maintenance","clutter","messy","overwhelm","management"],
    logo: ic("Spotless"),
  },
  {
    name: "Gemini",
    url: "https://setapp.com/apps/gemini",
    reason: "Find and delete every duplicate file on your Mac in minutes. Free up real storage without touching anything you need.",
    tags: ["productivity","organization","files","storage","efficiency","optimization","cleanup","speed","system","maintenance","clutter","messy","overwhelm","performance","management","workflow","automation"],
    logo: ic("Gemini"),
  },
  {
    name: "PDF Search",
    url: "https://setapp.com/apps/pdf-search",
    reason: "Search inside hundreds of PDFs at once — not just file names. Find the exact line you're looking for in seconds.",
    tags: ["productivity","documents","text","study","research","learning","reading","information","organization","business","admin","workflow","analysis","data","accuracy","pdf","efficiency","optimization","search","structure","retrieval","mental-load","clarity","files","capture"],
    logo: ic("PDF Search"),
  },
  {
    name: "TextSniper",
    url: "https://setapp.com/apps/textsniper",
    reason: "See text you can't select? TextSniper grabs it anyway — from videos, images, PDFs, anything on your screen.",
    tags: ["productivity","text","information","capture","screenshots","ocr","efficiency","shortcuts","optimization","documents","pdf","study","research","data","accuracy","workflow","organization","business","admin","output"],
    logo: ic("TextSniper"),
  },
  {
    name: "Ulysses",
    url: "https://setapp.com/apps/ulysses",
    reason: "Writing without distractions, published with one click. The app serious writers keep coming back to.",
    tags: ["writing","productivity","creative","content","communication","documents","focus","publishing","text","notes","organization","workflow","freelance","remote","documentation","pdf","efficiency","optimization","structure","deep-work","attention","clarity","output"],
    logo: ic("Ulysses"),
  },
  {
    name: "PopClip",
    url: "https://setapp.com/apps/popclip",
    reason: "Select any text and instantly translate it, search it, reformat it — no copying, no tab switching.",
    tags: ["productivity","writing","communication","text","workflow","efficiency","repetitive","shortcuts","optimization","search","context-switching","apps","performance","speed","output","documentation","information","tools"],
    logo: ic("PopClip"),
  },
  {
    name: "Keysmith",
    url: "https://setapp.com/apps/keysmith",
    reason: "Record any sequence of clicks and keystrokes once — then run it instantly, forever.",
    tags: ["productivity","automation","workflow","efficiency","repetitive","shortcuts","optimization","search","structure","retrieval","context-switching","apps","navigation","time-loss","tech","operations","business","admin","management","performance","system","output","scripting","macros"],
    logo: ic("Keysmith"),
  },
  {
    name: "BetterTouchTool",
    url: "https://setapp.com/apps/bettertouchtool",
    reason: "Make every input device do exactly what you want. Custom gestures, shortcuts, and window snapping all in one place.",
    tags: ["productivity","tech","automation","shortcuts","efficiency","repetitive","optimization","navigation","workflow","system","customization","performance","management","control","input-devices","gestures","clipboard-manager","screenshots","window-management","scripting","widgets","organization"],
    logo: ic("BetterTouchTool"),
  },
  {
    name: "Rocket Typist",
    url: "https://setapp.com/apps/rocket-typist",
    reason: "Keep every phrase, reply, and boilerplate you write in a searchable library — and expand any of them with a short abbreviation.",
    tags: ["productivity","writing","communication","documents","text","organization","business","admin","workflow","efficiency","repetitive","shortcuts","optimization","automation","search","structure","performance","speed","system","snippets","text-expansion"],
    logo: ic("Rocket Typist"),
  },
  {
    name: "Kerlig",
    url: "https://setapp.com/apps/kerlig",
    reason: "Your AI writing assistant lives in the menu bar. Hit a shortcut and it's there in any app — no browser tab needed.",
    tags: ["writing","communication","documents","text","productivity","workflow","efficiency","shortcuts","optimization","context-switching","research","information","analysis","data","business","remote","freelance","admin","content","publishing","focus","deep-work","attention","mental-load","clarity","pdf","email","apps","output","ai"],
    logo: ic("Kerlig"),
  },
  {
    name: "Elephas",
    url: "https://setapp.com/apps/elephas",
    reason: "Build your own AI brain from your documents and notes. Ask it anything and get answers with citations.",
    tags: ["productivity","writing","communication","documents","automation","text","study","research","learning","notes","information","organization","business","admin","operations","management","workflow","analysis","data","reports","documentation","capture","email","files","pdf","efficiency","repetitive","shortcuts","optimization","search","retrieval","context-switching","apps","deep-work","time-management","mental-load","clarity","performance","output","ai","knowledge-base"],
    logo: ic("Elephas"),
  },
  {
    name: "Lungo",
    url: "https://setapp.com/apps/lungo",
    reason: "Your Mac won't go to sleep mid-presentation. Lungo keeps it awake for exactly as long as you need.",
    tags: ["productivity","focus","efficiency","optimization","deep-work","attention","time-management","performance","system","maintenance","clarity","utility","workflow","automation","tools"],
    logo: ic("Lungo"),
  },
  {
    name: "One Switch",
    url: "https://setapp.com/apps/one-switch",
    reason: "One menu bar click does it all — clear your desktop, connect AirPods, turn on Do Not Disturb. Done.",
    tags: ["productivity","focus","efficiency","shortcuts","optimization","navigation","context-switching","distraction","deep-work","attention","clarity","performance","cleanup","speed","system","maintenance","clutter","messy","overwhelm","apps"],
    logo: ic("One Switch"),
  },
  {
    name: "Tab Finder",
    url: "https://setapp.com/apps/tabfinder",
    reason: "All your open tabs — every browser, every window — in one searchable list. Find anything in a keystroke.",
    tags: ["productivity","browsing","apps","efficiency","optimization","search","structure","retrieval","context-switching","navigation","time-loss","time-management","mental-load","clarity","clutter","messy","overwhelm","tabs","browser","overload","organization"],
    logo: ic("Tab Finder"),
  },
  {
    name: "Monarch",
    url: "https://setapp.com/apps/monarch",
    reason: "Hit a hotkey, type what you want, and it's done. Monarch makes your whole Mac feel faster.",
    tags: ["productivity","organization","workflow","efficiency","shortcuts","optimization","search","retrieval","context-switching","apps","navigation","time-management","clarity","speed","system","clutter","overwhelm","management","tasks","automation","tech"],
    logo: ic("Monarch"),
  },
  {
    name: "Amie",
    url: "https://setapp.com/apps/amie",
    reason: "It records your meetings, pulls out the action items, and drops them into your calendar. You just show up and talk.",
    tags: ["automation","productivity","organization","business","admin","operations","management","workflow","analysis","data","accuracy","meetings","documentation","capture","email","efficiency","optimization","search","structure","retrieval","tasks","todo","planning","tracking","time-management","mental-load","clarity","reminders","output"],
    logo: ic("Amie"),
  },
  {
    name: "Spellar AI",
    url: "https://setapp.com/apps/spellar-ai",
    reason: "Every meeting recorded privately, summarised instantly. Your notes are ready before you close the call.",
    tags: ["productivity","meetings","communication","documentation","capture","business","management","workflow","operations","efficiency","optimization","accuracy","analysis","clarity","organization","planning","remote","ai","summarization","integration","recording"],
    logo: ic("Spellar Al"),
  },
  {
    name: "Ready to Send",
    url: "https://setapp.com/apps/ready-to-send",
    reason: "Open your inbox and the replies are already drafted. Just edit, approve, and move on.",
    tags: ["productivity","writing","communication","business","admin","workflow","remote","clients","email","efficiency","automation","optimization","time-management","mental-load","clarity","overwhelm","output","ai","drafts","correspondence"],
    logo: ic("Ready to Send"),
  },
  {
    name: "Noizio",
    url: "https://setapp.com/apps/noizio",
    reason: "Rainstorm, coffee shop, deep space — pick your sound and let it carry you into focus.",
    tags: ["productivity","focus","creative","music","content","production","study","research","learning","deep-work","attention","mental-load","clarity","leisure","apps","efficiency","optimization","time-management","overwhelm","atmosphere","ambient","wellbeing"],
    logo: ic("Noizio"),
  },
  {
    name: "Be Focused",
    url: "https://setapp.com/apps/be-focused",
    reason: "A task list that runs a focus timer. Work in bursts, take real breaks, and actually get through your to-do list.",
    tags: ["productivity","organization","management","workflow","freelance","remote","analysis","data","efficiency","optimization","tasks","todo","planning","tracking","focus","deep-work","attention","time-management","mental-load","clarity","performance","overwhelm","reminders","output"],
    logo: ic("Be Focused"),
  },
  {
    name: "Soulver",
    url: "https://setapp.com/apps/soulver",
    reason: "Write maths like you'd say it out loud and Soulver solves it. Budgets, conversions, currency — no formula syntax.",
    tags: ["finance","productivity","organization","business","admin","management","analysis","data","accuracy","efficiency","optimization","tracking","planning","time-management","mental-load","clarity","reminders","overwhelm","budgeting","tech","automation","terminal","notes","writing","study","learning","information","workflow","reports","systems","documentation","structure","retrieval","tasks","output"],
    logo: ic("Soulver"),
  },
  {
    name: "Chronicle",
    url: "https://setapp.com/apps/chronicle",
    reason: "Never pay a late fee again. Chronicle tracks every bill and nudges you before it's due.",
    tags: ["finance","productivity","organization","business","admin","management","analysis","data","accuracy","efficiency","optimization","tracking","planning","time-management","mental-load","clarity","reminders","overwhelm","budgeting"],
    logo: ic("Chronicle"),
  },
  {
    name: "Timemator",
    url: "https://setapp.com/apps/timemator",
    reason: "It watches what you work on and logs it automatically. Client billing and time reports with zero manual effort.",
    tags: ["productivity","time-management","tracking","business","automation","workflow","freelance","finance","analysis","reports","data","accuracy","efficiency","optimization","management","organization","tech","development","design","creative","remote","clients","admin","structure","tasks","planning","mental-load","clarity","performance","overwhelm","output"],
    logo: ic("Timemator"),
  },
  {
    name: "MindNode Classic",
    url: "https://setapp.com/apps/mindnode",
    reason: "Get your thinking out of your head and onto a canvas. Ideas become clearer the moment you start connecting them.",
    tags: ["productivity","creative","design","writing","focus","study","research","learning","notes","information","organization","management","workflow","analysis","data","capture","efficiency","optimization","structure","planning","tracking","deep-work","time-management","mental-load","clarity","overwhelm"],
    logo: ic("MindNode Classic"),
  },
  {
    name: "Muse",
    url: "https://setapp.com/apps/muse",
    reason: "A whiteboard that actually thinks with you. Drop in PDFs, notes, and sketches — and watch the big picture emerge.",
    tags: ["productivity","creative","design","visual","writing","communication","study","research","learning","notes","information","organization","business","management","workflow","analysis","data","pdf","efficiency","optimization","structure","retrieval","planning","tracking","mental-load","clarity","overwhelm","output"],
    logo: ic("Muse"),
  },
  {
    name: "HoudahSpot",
    url: "https://setapp.com/apps/houdahspot",
    reason: "Spotlight on steroids. Search by name, text, date, tag, size — and combine them to find anything instantly.",
    tags: ["productivity","organization","information","research","search","structure","retrieval","files","documents","efficiency","optimization","accuracy","context-switching","navigation","clarity","performance","system","management","workflow"],
    logo: ic("HoudahSpot"),
  },
  {
    name: "Lacona",
    url: "https://setapp.com/apps/lacona",
    reason: "Type what you want to do in plain English and Lacona does it. Launch apps, search files, set reminders — naturally.",
    tags: ["productivity","automation","workflow","efficiency","shortcuts","optimization","search","retrieval","context-switching","apps","navigation","tasks","planning","time-management","mental-load","clarity","speed","system","reminders","output","management","organization","information","capture"],
    logo: ic("Lacona"),
  },
  {
    name: "Permute",
    url: "https://setapp.com/apps/permute",
    reason: "Convert any video, audio, or image to any format with a drag and a drop. No settings, no stress.",
    tags: ["creative","video","music","editing","content","visual","production","photos","design","media","files","pdf","efficiency","automation","shortcuts","optimization","workflow","productivity","output"],
    logo: ic("Permute"),
  },
  {
    name: "PDF Pals",
    url: "https://setapp.com/apps/pdf-pals",
    reason: "Chat with your PDFs like they're a colleague. Ask questions, get cited answers — all offline.",
    tags: ["productivity","documents","text","study","research","learning","reading","information","organization","business","admin","analysis","data","pdf","efficiency","optimization","search","structure","retrieval","context-switching","mental-load","clarity","output"],
    logo: ic("PDF Pals"),
  },
  {
    name: "Numerics",
    url: "https://setapp.com/apps/numerics",
    reason: "Your KPIs and business stats in one dashboard. Know how you're performing without opening five different tools.",
    tags: ["business","productivity","management","analysis","data","reports","analytics","marketing","sales","growth","finance","operations","workflow","tracking","organization","efficiency","optimization","clarity","automation","systems","performance","information","visual"],
    logo: ic("Numerics"),
  },
  {
    name: "BusyCal",
    url: "https://setapp.com/apps/busycal",
    reason: "A calendar that actually earns its place. Natural language scheduling, integrated to-dos, and travel time built right in.",
    tags: ["productivity","organization","business","admin","management","workflow","efficiency","optimization","tasks","todo","planning","tracking","time-management","mental-load","clarity","reminders","overwhelm","calendar","scheduling"],
    logo: ic("BusyCal"),
  },
  {
    name: "Marked",
    url: "https://setapp.com/apps/marked",
    reason: "Preview your Markdown as you write it, check your prose for weaknesses, and export anywhere in one click.",
    tags: ["writing","communication","documents","focus","publishing","text","study","research","learning","notes","reading","information","organization","workflow","analysis","data","accuracy","documentation","efficiency","optimization","structure","retrieval","mental-load","clarity","output"],
    logo: ic("Marked"),
  },
];

export const TAG_MAP = {
  "Coding or tech stuff":         ["tech","code","development","engineering","terminal","api","backend","debugging","productivity","automation","workflow"],
  "Creative work (design, video, music)": ["creative","design","video","music","audio","image","visual","content","production","editing","multimedia","animation"],
  "Writing or editing":           ["writing","editing","content","text","communication","documentation","publishing","markdown","focus","productivity"],
  "Studying or research":         ["study","research","learning","reading","notes","information","organization","focus","academic","education"],
  "Business or admin tasks":      ["business","admin","operations","management","documents","workflow","productivity","organization","planning","tracking"],
  "Freelancing or remote work":   ["freelance","remote","clients","communication","productivity","workflow","tasks","collaboration","flexibility","time-management"],
  "Finance or consulting":        ["finance","consulting","analysis","data","reports","accuracy","documents","productivity","planning","tracking"],
  "Sales or marketing":           ["sales","marketing","growth","communication","analytics","social-media","content","outreach","engagement","crm"],
  "Industry or public services":  ["operations","management","systems","compliance","logistics","productivity","organization","tracking","workflow","reporting"],
  "Just for fun (entertainment)": ["entertainment","media","streaming","browsing","leisure","video","music","apps","discovery","experience"],

  "Taking notes or writing up meetings": ["notes","meetings","documentation","writing","capture","organization","productivity","workflow","information","retrieval"],
  "Writing (emails, posts, messages)":   ["writing","communication","email","text","editing","content","productivity","workflow","documentation","publishing"],
  "Managing files (screenshots, PDFs, etc.)": ["files","file-management","documents","pdf","screenshots","storage","organization","retrieval","workflow","compression"],
  "Repeating the same small tasks":      ["automation","repetitive","efficiency","workflow","productivity","shortcuts","optimization","time-saving","scripting"],
  "Finding or organizing things":        ["organization","search","files","notes","retrieval","structure","productivity","information","management","workflow"],
  "Switching between apps":              ["workflow","context-switching","productivity","efficiency","focus","apps","navigation","time-management","overload"],
  "Keeping track of tasks or to-dos":    ["tasks","todo","planning","tracking","productivity","organization","management","workflow","reminders","time-management"],
  "Staying focused and avoiding distractions": ["focus","distraction","deep-work","attention","productivity","mental-load","clarity","time-management","overwhelm"],
  "Many things — my Mac feels slow":     ["performance","speed","cleanup","system","maintenance","clutter","optimization","efficiency","stability"],

  "My Mac is kind of a mess":              ["clutter","organization","cleanup","files","system","management","messy","optimization","structure"],
  "I get distracted or overwhelmed easily":["distraction","focus","overwhelm","attention","mental-load","productivity","clarity","deep-work","time-management"],
  "I often forget tasks":                  ["tasks","todo","memory","reminders","planning","tracking","organization","productivity","workflow"],
  "I have too many tabs open":             ["tabs","browser","overload","organization","navigation","focus","productivity","workflow","distraction"],
  "I feel busy, but not productive":       ["productivity","efficiency","workflow","time-management","optimization","focus","output","clarity","mental-load"],
  "I repeat the same actions every day":   ["automation","repetitive","efficiency","workflow","productivity","optimization","time-saving","shortcuts","scripting"],
  "I lose track of files, notes, or info": ["organization","files","notes","search","retrieval","management","information","structure","productivity"],
};

export const Q1 = [
  "Coding or tech stuff",
  "Creative work (design, video, music)",
  "Writing or editing",
  "Studying or research",
  "Business or admin tasks",
  "Freelancing or remote work",
  "Finance or consulting",
  "Sales or marketing",
  "Industry or public services",
  "Just for fun (entertainment)",
];

export const Q2 = [
  "Taking notes or writing up meetings",
  "Writing (emails, posts, messages)",
  "Managing files (screenshots, PDFs, etc.)",
  "Repeating the same small tasks",
  "Finding or organizing things",
  "Switching between apps",
  "Keeping track of tasks or to-dos",
  "Staying focused and avoiding distractions",
  "Many things — my Mac feels slow",
];

export const Q3 = [
  "My Mac is kind of a mess",
  "I get distracted or overwhelmed easily",
  "I often forget tasks",
  "I have too many tabs open",
  "I feel busy, but not productive",
  "I repeat the same actions every day",
  "I lose track of files, notes, or info",
];